### ISSUE TITLE
TXT generation fails while HTML and PDF succeed, error message is unhelpful

### ISSUE THREAD

**Issue by jgscudder** [ietf-tools/ietf-at-ui#85]
The attached XML fails to render as txt, with the unhelpful error message "xml2rfc error: text generation error". PDF and HTML succeed. I accept that there might be something wrong with the XML (which is quite old), but the error message doesn't help me figure out what it is.

For that matter, it would be nice to be able to see the more verbose errors-and-warnings form the old xml2rfc site offered.

P.S.: GitHub refused XML attachment, so I added a TXT extension to the attachment to circumvent that
[test.xml.txt](https://github.com/ietf-tools/ietf-at-ui/files/8584931/test.xml.txt)
.

**Comment by jgscudder** [comment]
By trial-and-error I worked out that the problem in the XML is the inclusion of

<?rfc toc="no"?>

Obvs this doesn't change the fact that the error message is unhelpful.

**Comment by kesara** [comment]
Thanks for the bug report.
In this case, `xml2rfc` crashed and failed to generate a meaningful error message.
I'm transferring this issue to [xml2rfc](https://github.com/ietf-tools/xml2rfc).

```
Traceback (most recent call last):
  File "/Users/kesara/lab/xml2rfc/venv/bin/xml2rfc", line 33, in <module>
    sys.exit(load_entry_point('xml2rfc==3.12.4', 'console_scripts', 'xml2rfc')())
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.9/site-packages/xml2rfc-3.12.4-py3.9.egg/xml2rfc/run.py", line 742, in main
    writer.write(filename)
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.9/site-packages/xml2rfc-3.12.4-py3.9.egg/xml2rfc/writers/text.py", line 345, in write
    text = self.process()
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.9/site-packages/xml2rfc-3.12.4-py3.9.egg/xml2rfc/writers/text.py", line 302, in process
    self.add_pageno_placeholders()
  File "/Users/kesara/lab/xml2rfc/venv/lib/python3.9/site-packages/xml2rfc-3.12.4-py3.9.egg/xml2rfc/writers/text.py", line 374, in add_pageno_placeholders
    for e in toc.xpath('.//xref[2]'):
AttributeError: 'NoneType' object has no attribute 'xpath'
```
